version: "2.3"



services:
  test-3.0:
    build:
      context: .
      args:
        RUBY_VERSION: 3.0
    image: worker-killer-tests:3.0
    working_dir: /home/app
    
  test-3.1:
    build:
      context: .
      args:
        RUBY_VERSION: 3.1
    image: worker-killer-tests:3.1
    working_dir: /home/app
    
    


